name: dns-server

services:
    server:
        hostname: $FQDN_HOSTNAME
        networks:
            - dns-network
        image: public.ecr.aws/c0y5g8k0/dns-server$ENV_NAME
        pull_policy: missing
        deploy:
            resources:
                limits:
                    cpus: "0.4" # Limits to half a CPU core
                    memory: 512M # Often set together with CPU
        logging:
            driver: json-file
            options:
                max-size: "10m" # Maximum size of each log file
                max-file: "3" # Maximum number of log files to keep
                compress: "true" # Compress rotated log files to save space
        ports:
            - "53:53/udp"
            - "53:53/tcp"
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - UPSTREAM=${UPSTREAM}
            - LEVEL=${LEVEL}
        restart: always
        depends_on:
            redis:
                restart: true
                condition: service_healthy
                required: true
    redis:
        networks:
            - dns-network
        image: redis:latest
        pull_policy: missing
        ports:
            - "6379:6379"
        restart: always
        volumes:
            - ./db:/data
        logging:
            driver: json-file
            options:
                max-size: "10m" # Maximum size of each log file
                max-file: "3" # Maximum number of log files to keep
                compress: "true" # Compress rotated log files to save space
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s
    adguard-doh:
        image: adguard/dnsproxy:v0.75.4
        networks:
            - dns-network
        depends_on:
            redis:
                restart: true
                condition: service_healthy
                required: true
            server:
                restart: true
                condition: service_healthy
                required: true
        restart: always
        logging:
            driver: json-file
            options:
                max-size: "10m" # Maximum size of each log file
                max-file: "3" # Maximum number of log files to keep
                compress: "true" # Compress rotated log files to save space
        volumes:
            - ./dnsproxy/config.yaml:/opt/dnsproxy/config.yaml
            - /etc/letsencrypt/live/${FQDN_HOSTNAME}/fullchain.pem:/ssl/fullchain.pem
            - /etc/letsencrypt/live/${FQDN_HOSTNAME}/privkey.pem:/ssl/privkey.pem
        ports:
            - "443:443"
            - "443:443/udp"
            - "853:853"
            - "853:853/udp"
networks:
    dns-network:
